import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { AllUsersProvider } from '@/shared/context/AllUsersContextProps '
import { DBUserProvider } from '@/shared/context/DBUserProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactElement | React.ReactElement[]
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AllUsersProvider>
          <DBUserProvider>
            {children}
          </DBUserProvider>
        </AllUsersProvider>
      </body>
    </html>
  )
}
